[package]
name = "ledcat"
description = "Control lots of LED's over lots of protocols"
version = "0.1.4"
repository = "https://github.com/polyfloyd/ledcat"
authors = ["polyfloyd <floyd@polyfloyd.net>"]
readme = "README.md"
license = "GPL-3.0"
keywords = ["leds", "led-strips", "artnet", "ws2812b"]
categories = ["command-line-utilities", "embedded", "hardware-support"]

[badges]
travis-ci = { repository = "polyfloyd/ledcat", branch = "master" }

[features]
default = []
ci = []

[dependencies]
byteorder = "1.2.2"
clap = "2.31.2"
clippy = { version = "0.0.*", optional = true }
derive-error = "0.0.4"
gpio = { path = "components/gpio", version = "0.3.0" }
net2 = "0.2.31"
nix = "0.10.0"
regex = "0.2.10"

[dev-dependencies]
assert_cli = "0.5.4"
rand = "0.4.2"
tempdir = "0.3.6"
