[package]
name = "ledcat"
description = "Control lots of LED's over lots of protocols"
version = "0.1.2"
repository = "https://github.com/polyfloyd/ledcat"
authors = ["polyfloyd <floyd@polyfloyd.net>"]
readme = "README.md"
license = "GPL-3.0"
keywords = ["leds", "led-strips", "artnet", "ws2812b"]
categories = ["command-line-utilities", "embedded", "hardware-support"]

[badges]
travis-ci = { repository = "polyfloyd/ledcat", branch = "master" }

[features]
default = []

[dependencies]
byteorder = "1.2.1"
clap = "2.29.0"
clippy = { version = "0.0.*", optional = true }
derive-error = "0.0.4"
gpio = { path = "components/gpio", version = "0.3.0" }
libc = "0.2.29"
nix = "0.9.0"
regex = "0.2.3"

[dev-dependencies]
assert_cli = "0.5.4"
rand = "0.4.1"
tempdir = "0.3.5"
