[package]
name = "ledcat"
version = "0.0.1"
authors = ["polyfloyd <floyd@polyfloyd.net>"]

[dependencies]
byteorder = "~1.0.0"
clap = "~2.20.0"
ioctl = "~0.3.3"
libc = "^0.2.18"
regex = "~0.2.1"

[dev-dependencies]
tempdir = "~0.3"
