[package]
name = "ledcat"
version = "0.0.1"
authors = ["polyfloyd <floyd@polyfloyd.net>"]

[dependencies]
byteorder = "~1.1.0"
clap = "~2.26.0"
derive-error = "^0.0.3"
ioctl = { version = "0.3.4", git = "https://github.com/cmr/ioctl.git" }
libc = "^0.2.29"
nix = "~0.9.0"
regex = "~0.2.2"

[dev-dependencies]
tempdir = "~0.3"
