[package]
name = "ledcat"
description = "Ledcat is simple utility that aims to provide a standard interface for driving LED-strips and such"
version = "0.0.1"
authors = ["polyfloyd <floyd@polyfloyd.net>"]
license = "GPL-3.0"

[dependencies]
byteorder = "~1.1.0"
clap = "~2.26.0"
derive-error = "^0.0.3"
gpio = "~0.3.0"
libc = "^0.2.29"
nix = "~0.9.0"
regex = "~0.2.2"

[dev-dependencies]
tempdir = "~0.3"
